name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/check@v3

      - name: print hello world
        run: echo "Hello World"